### ISSUE TITLE
Filtering by date

### ISSUE THREAD

**Issue by amorphid** [AceFire6/ordered-arrowverse#22] opened 2018-06-10 18:56 UTC
Hey there.  This app is a nice little resource.  Thanks!

I'd love for there to be a filter for excluding shows in a certain range, too.  The use case is that I'd like to all episodes for each show's most recent season without scrolling.  Writing a bunch of code is clearly easier than scrolling down the list (no, not really, but writing code is fun).

If you don't plan on writing this feature yourself, would you be open to a pull request?  It'd probably need to change how filtering works a little bit, as filtering now only allows one to exclude shows.

My first pass at thinking up a couple options how to add this feature:

-  Adding a second filter to exclude by date:
  - one filter is the original for excluding shows
  - the second would be a filter for excluding dates
- Filtering is in an expandable list
  - There a "Show Filter Options" button or link, and clicking on it expands the list
  - This list includes N filtering options, which be filtering by date or range
  - If easy enough to do, one could bookmark the filtered list, too!

Thoughts on how to filter by date:

- Before a specific date
  - "I want to watch episodes before May 15, 2013" (Arrow, season 1)
- After a specific date
  - "I want to watch episodes after October 9, 2017" (every show's most recent reason)
  - "I want to watch every episode since March 1, 2018" (I've watched everything up to that point)
- Between two dates
  - "I want to watch every episode between November 1, 2015 and December 1, 2015" (I have fond memories of that time, and want to relive the experience!)

**Comment by AceFire6** [comment] 2018-06-11 11:02
Hi @amorphid

Thanks for making an issue. This seems like a cool idea. I don't mind if you make a PR.

Unfortunately, a lot of the issues on the board currently are things I really want to do but don't have time for.

I'll give you a review if you do 👍

**Comment by cyphix333** [comment] 2018-08-06 11:25
I like this idea - kinda annoying having to find the most recent seasons all the time haha :)

**Comment by amorphid** [comment] 2018-08-06 12:42
> I like this idea - kinda annoying having to find the most recent seasons all the time haha :)

Unfortunately also I got busy & no longer have time to work on it.  Save us @cyphix333, you're our hope :)

**Comment by cyphix333** [comment] 2018-08-06 18:46
LOL I'm also time poor right now.

**Comment by AceFire6** [comment] 2018-08-07 08:13
I should be able to do this within the next two weeks 👍

The hardest part for me is always the UI 😛 

Adding in the filtering itself should be fairly simple

**Comment by cyphix333** [comment] 2018-08-07 08:52
Awesome!

@AceFire6 I also sent you an email about the "Crisis on Earth-X" being jumbled, hopefully you got it :)

**Comment by AceFire6** [comment] 2018-09-18 21:13
@amorphid I've finally gotten around to finishing this! It's been released. I'm going to tweak how the filtering looks, but until I get to the redesign it'll have to be simple.

I hope you enjoy it! 😄

**Comment by amorphid** [comment] 2018-09-19 16:44
Aw yiss!  I will most definitely enjoy it :)

**Comment by zoidbergwill** [comment] 2018-09-19 19:40
@cyphix333 You're always welcome to submit a PR. 

You should also probably file issues instead of e-mailing maintainers. 🤔

**Comment by cyphix333** [comment] 2018-09-19 20:09
@zoidbergwill I already emailed him per the link on his site before posting here, which got ignored as well. So I really don't see the point TBH.

**Comment by AceFire6** [comment] 2018-09-19 21:45
Hi @cyphix333. Thanks for raising your concerns. 

Unfortunately, it seems the host I was using for the old email address listed on the site was terrible. I sent a few test emails now, and none went through. I also searched the email server and couldn't find any emails from you. It seems they were lost too.

I've updated the email to a Gmail address in the hopes that it will be more reliable. The new email is arrowverse.info@gmail.com.

I've always tried to ensure that I reply to all the emails I get (some people used my GitHub email address). So it's sad that I've missed out on any that went to the old address.

The integrity of the list is and should be the highest priority. Without that integrity, there is no reason for the site to exist. Unfortunately, maintaining the site is a best-effort attempt on my part as I work full-time and am pursuing my Master's.

This issue was initially reported in #15 and fixed as of https://github.com/AceFire6/ordered-arrowverse/commit/136be462a092c0f077d27eede9219f02d7c98700. It seems the bug must have returned as a regression at some point.

I've made an issue regarding the incorrect ordering of the Crisis on Earth-X (#55). Hopefully, I can get to writing up a rule to fix that in the next week.

Thank you
Jethro

**Closed by AceFire6** 2018-09-19 21:45 UTC
Labels: enhancement

**Comment by cyphix333** [comment] 2018-09-20 10:48
@AceFire6 Thanks a lot for the response Jethro. Appreciate the list and the new features, but yes, agree that integrity of the list should be of the highest priority. :)

Looks like this has been developed in Python, unfortunately I am not a Python dev so can't really help there. :(
